b-server1:
  properties:
    attributes:
      nodename: b-server1
      packages:
        install:
          - jq
          - rsync
        remove:
          - wpasupplicant
    run_list:
      - recipes/b-server.rb
