apiVersion: v1
kind: Service
metadata:
  name: kubernetes
  labels:
    component: apiserver
    provider: kubernetes
spec:
  ports:
  - name: https
    port: 443
    protocol: TCP
  loadBalancerIP: 172.16.177.1
  type: LoadBalancer
