apiVersion: "cilium.io/v2alpha1"
kind: CiliumBGPPeeringPolicy
metadata:
  name: default
spec: # CiliumBGPPeeringPolicySpec
  virtualRouters: # []CiliumBGPVirtualRouter
    - localASN: 65003
      exportPodCIDR: true
      serviceSelector:
        matchExpressions:
          - { key: dummy, operator: NotIn, values: ["never-used-value"] }
      neighbors: # []CiliumBGPNeighbor
        - peerAddress: ::1/128
          peerASN: 65002
          holdTimeSeconds: 5
          keepAliveTimeSeconds: 3
          gracefulRestart:
            enabled: true
            restartTimeSeconds: 120
