miyakojima:
  properties:
    role: k8s-node
    attributes:
      machine: Geekom IT11

irabujima:
  properties:
    role: k8s-node
    attributes:
      machine: NanoPi R4S
      containerd:
        state_dir: /var/cache/containerd

kurimajima:
  properties:
    role: k8s-node
    attributes:
      machine: NanoPi R4S
      containerd:
        state_dir: /var/cache/containerd
