b-server1:
  properties:
    role: b-server
    attributes:
      machine: NanoPi R4S

b-server2:
  properties:
    role: b-server
    attributes:
      machine: NanoPi R4S

b-server3:
  properties:
    role: b-server
    attributes:
      machine: Raspberry Pi 4

miyakojima:
  properties:
    role: pve
    attributes:
      machine: Geekom IT11

cluster-api:
  properties:
    role: cluster-api
    attributes:
      machine: QEMU
